experiment: 04172333_PanopLi_mlp+grid_bim316_pureed-pasta
seed: 541
save_epoch: 1
sanity_steps: -1
max_epoch: 10
val_check_percent: 1.0
val_check_interval: 0.25
subsample_frames: 1
feat_grid_dim: 24
segment_grouping_mode: argmax_conf
semantic_weight_mode: softmax
late_semantic_optimization: 0
use_symmetric_ce: false
probabilistic_ce_mode: NoTTAConf
use_feature_regularization: false
samples_num: 32
lambda_feat: 0.04
ce_alpha: 0.85
ce_beta: 0.15
lr: 0.0005
lambda_segment: 0.8
lambda_semantics: 0.1
lambda_instances: 0.1
lambda_rgb: 1
lambda_dist_reg: 0.005
lambda_depth: 10.0
weight_class_0: 0
weight_decay: 1.0e-08
stop_semantic_grad: true
use_mlp_for_semantics: true
decay_step:
- 9
- 10
decay_gamma: 0.5
warmup_epochs: 0
warmup_multiplier: 1.0
batch_size: 4096
max_rays_instances: 1024
max_rays_segments: 1024
batch_size_contrastive: 1
batch_size_segments: 32
max_instances: 50
chunk: 2048
chunk_segment: 16384
num_workers: 8
logger: tb
overfit: false
min_grid_dim: 256
max_grid_dim: 192
lambda_tv_density: 0.1
lambda_tv_semantics: 0.02
lambda_tv_appearance: 0.01
bbox_aabb_reset_epochs:
- 1
- 2
- 3
grid_upscale_epochs:
- 1
- 2
- 3
- 4
instance_optimization_epoch: 3
segment_optimization_epoch: 6
perturb: 1.0
noise_std: 1.0
decay_noise: 20000
max_depth: 5.0
reweight_fg: false
dataset_class: panopli
dataset_root: /home/fgm/disk1/Focus/code/panoptic-lifting/data/bim316
image_dim:
- 512
- 512
visualized_indices: null
densitynet_weight_path: null
grid_weight_path: /home/fgm/disk1/Focus/code/panoptic-lifting/data/bim316/tsdf_grid_mxd_5_dim_256.pt
depth_scale: 1000.0
wandb_main: false
suffix: -dev
depth_z2d: false
tsdf_dim: 512
